/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MapRouteImport } from './routes/map'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ScreenshotImportRouteImport } from './routes/screenshot-import'
import { Route as TechniciansRouteImport } from './routes/technicians'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotImportRoute = ScreenshotImportRouteImport.update({
  id: '/screenshot-import',
  path: '/screenshot-import',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cluster': typeof ClusterRoute
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/schedule': typeof ScheduleRoute
  '/screenshot-import': typeof ScreenshotImportRoute
  '/technicians': typeof TechniciansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cluster': typeof ClusterRoute
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/schedule': typeof ScheduleRoute
  '/screenshot-import': typeof ScreenshotImportRoute
  '/technicians': typeof TechniciansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cluster': typeof ClusterRoute
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/schedule': typeof ScheduleRoute
  '/screenshot-import': typeof ScreenshotImportRoute
  '/technicians': typeof TechniciansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cluster'
    | '/import'
    | '/map'
    | '/schedule'
    | '/screenshot-import'
    | '/technicians'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cluster'
    | '/import'
    | '/map'
    | '/schedule'
    | '/screenshot-import'
    | '/technicians'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cluster'
    | '/import'
    | '/map'
    | '/schedule'
    | '/screenshot-import'
    | '/technicians'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClusterRoute: typeof ClusterRoute
  ImportRoute: typeof ImportRoute
  MapRoute: typeof MapRoute
  ScheduleRoute: typeof ScheduleRoute
  ScreenshotImportRoute: typeof ScreenshotImportRoute
  TechniciansRoute: typeof TechniciansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshot-import': {
      id: '/screenshot-import'
      path: '/screenshot-import'
      fullPath: '/screenshot-import'
      preLoaderRoute: typeof ScreenshotImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClusterRoute: ClusterRoute,
  ImportRoute: ImportRoute,
  MapRoute: MapRoute,
  ScheduleRoute: ScheduleRoute,
  ScreenshotImportRoute: ScreenshotImportRoute,
  TechniciansRoute: TechniciansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
